spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=sportcenterautomation@gmail.com
mail.smtp.password=
mail.smtp.auth=true
mail.smtp.starttls.enable=true
